// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5UmWxDtoojbvstfJFaV8E39zpnr5NlU',
    appId: '1:813229236940:web:ca2d0aadc0a148f5dfd869',
    messagingSenderId: '813229236940',
    projectId: 'projectflutter-d7cb4',
    authDomain: 'projectflutter-d7cb4.firebaseapp.com',
    storageBucket: 'projectflutter-d7cb4.firebasestorage.app',
    measurementId: 'G-WXM1XWQYW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnV1EtVrvzOdE0etvrxKJGhrDk-7UPgA',
    appId: '1:813229236940:android:a1a2bc8e4ce5b40adfd869',
    messagingSenderId: '813229236940',
    projectId: 'projectflutter-d7cb4',
    storageBucket: 'projectflutter-d7cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCkgCDPgUI1qi3CJ0kOQWpEwbkHdmFrks',
    appId: '1:813229236940:ios:95e9547df95277ecdfd869',
    messagingSenderId: '813229236940',
    projectId: 'projectflutter-d7cb4',
    storageBucket: 'projectflutter-d7cb4.firebasestorage.app',
    iosBundleId: 'com.example.cyberGuardAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCkgCDPgUI1qi3CJ0kOQWpEwbkHdmFrks',
    appId: '1:813229236940:ios:95e9547df95277ecdfd869',
    messagingSenderId: '813229236940',
    projectId: 'projectflutter-d7cb4',
    storageBucket: 'projectflutter-d7cb4.firebasestorage.app',
    iosBundleId: 'com.example.cyberGuardAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5UmWxDtoojbvstfJFaV8E39zpnr5NlU',
    appId: '1:813229236940:web:0d0e5f6edd741dfddfd869',
    messagingSenderId: '813229236940',
    projectId: 'projectflutter-d7cb4',
    authDomain: 'projectflutter-d7cb4.firebaseapp.com',
    storageBucket: 'projectflutter-d7cb4.firebasestorage.app',
    measurementId: 'G-GLS4G17HBX',
  );
}
